Repository GSG-G8/art-gallery, pull requests merged in 2020-06, with the labels that each got.

#11 4 file structure
  .eslintrc.json
  .gitignore
  .travis.yml
  .vscode/settings.json
  client/.eslintrc.json
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/app/index.js
  client/src/app/style.css
  client/src/assets/icons/.gitkeep
  client/src/assets/images/.gitkeep
  client/src/components/index.js
  client/src/constants/routes.js
  client/src/containers/index.js
  client/src/index.js
  package-lock.json
  package.json
  server/app.js
  server/controllers/index.js
  server/database/connection.js
  server/database/data/build.js
  server/database/data/build.sql
  server/database/data/fakeData.sql
  server/index.js
  server/utils/validation/index.js
  test/index.test.js
Labels: Awaiting Review, EPIC

#24 5 server set up
  client/package-lock.json
  client/package.json
  package-lock.json
  package.json
  server/app.js
  server/controllers/errorHandlers/index.js
  server/controllers/index.js
  server/index.js
Labels: Awaiting Review, Backend

#26 build schema
  package.json
  server/database/connection.js
  server/database/data/build.js
  server/database/data/build.sql
  server/database/data/buildDatabase.sql
Labels: Awaiting Review, Backend, Database

#29 Insert a fake data to database
  package.json
  server/database/data/fakeData.sql
Labels: Awaiting Review, Backend, Database

#30 GET | paintings
  .travis.yml
  server/app.js
  server/controllers/getPaintings.js
  server/controllers/index.js
  server/database/queries/Paintings/getPaintingsQuery.js
  server/database/queries/Paintings/index.js
  server/database/queries/index.js
  server/routes/index.js
  server/routes/paintings.js
  test/paintings.test.js
Labels: Awaiting Review, Backend, Reference

#28 POST /login
  package.json
  server/controllers/auth.js
  server/controllers/index.js
  server/database/data/fakeData.sql
  server/database/queries/artists/getArtist.js
  server/database/queries/artists/index.js
  server/database/queries/users/getUser.js
  server/database/queries/users/index.js
  server/routes/auth.js
  server/routes/index.js
  server/utils/validation/index.js
  server/utils/validation/loginSchema.js
  test/auth.test.js
Labels: Awaiting Review, Backend

#32 GET | paintings artist
  server/controllers/getArtistPaints.js
  server/controllers/index.js
  server/database/queries/Paintings/getArtistPaintsQuery.js
  server/database/queries/Paintings/index.js
  server/database/queries/index.js
  server/routes/paintings.js
  test/paintings.test.js
Labels: Awaiting Review, Backend, Database

#33 10 signup
  package-lock.json
  package.json
  server/app.js
  server/controllers/auth.js
  server/controllers/errorHandlers/index.js
  server/controllers/index.js
  server/database/queries/artists/addArtist.js
  server/database/queries/artists/checkArtistExist.js
  server/database/queries/artists/index.js
  server/database/queries/customers/addCustomer.js
  server/database/queries/customers/checkCustomerEmail.js
  server/database/queries/customers/index.js
  server/database/queries/index.js
  server/routes/auth.js
  server/utils/addUser.js
  server/utils/validation/index.js
  server/utils/validation/loginSchema.js
  server/utils/validation/registerSchema.js
  test/register.test.js
Labels: Approved, Backend

#38 GET | logout
  server/controllers/auth.js
  server/routes/auth.js
  test/auth.test.js
Labels: Awaiting Review, Backend

#31 handle get profile artist route
  server/controllers/getArtist.js
  server/controllers/index.js
  server/database/queries/artists/getArtistQuery.js
  server/database/queries/artists/index.js
  server/database/queries/index.js
  server/routes/artist.js
  server/routes/index.js
  test/artist.test.js
Labels: Awaiting Review, Backend

#34 POST | painting
  package-lock.json
  package.json
  server/app.js
  server/controllers/errorHandlers/index.js
  server/controllers/index.js
  server/controllers/middlewares/verifyUser.js
  server/controllers/paintings/addPainting.js
  server/controllers/paintings/getArtistPaints.js
  server/controllers/paintings/getPaintings.js
  server/controllers/paintings/index.js
  server/controllers/user/getArtist.js
  server/controllers/user/index.js
  server/database/queries/Paintings/addPainting.js
  server/database/queries/Paintings/index.js
  server/database/queries/index.js
  server/routes/index.js
  server/routes/paintings.js
  server/utils/uploadImg.js
  server/utils/validation/addPaintingSchema.js
  server/utils/validation/index.js
  test/1610-Brain-Games-Study-workout.jpg
  test/paintings.test.js
Labels: Approved, Backend

#35 POST | Cart
  package-lock.json
  server/app.js
  server/controllers/Artist/getArtist.js
  server/controllers/Artist/index.js
  server/controllers/Cart/addPaintingToCart.js
  server/controllers/Cart/index.js
  server/controllers/Paintings/getArtistPaints.js
  server/controllers/Paintings/getPaintings.js
  server/controllers/Paintings/index.js
  server/controllers/index.js
  server/controllers/middlewares/verifyUser.js
  server/database/data/build.sql
  server/database/data/fakeData.sql
  server/database/queries/Cart/index.js
  server/database/queries/Cart/postCartQuery.js
  server/database/queries/index.js
  server/routes/cart.js
  server/routes/index.js
  test/cart.test.js
Labels: Awaiting Review, Backend, Database

#36 19 delete painting from cart
  package.json
  server/controllers/Artist/getArtist.js
  server/controllers/Artist/index.js
  server/controllers/Cart/index.js
  server/controllers/Paintings/getArtistPaints.js
  server/controllers/Paintings/getPaintings.js
  server/controllers/Paintings/index.js
  server/controllers/cart/addPaintingToCart.js
  server/controllers/cart/deletePaintingCart.js
  server/controllers/cart/index.js
  server/controllers/index.js
  server/controllers/middleware/index.js
  server/controllers/middleware/verifyUser.js
  server/database/queries/Cart/index.js
  server/database/queries/Paintings/getPaintingsUser.js
  server/database/queries/Paintings/index.js
  server/database/queries/cart/deletePaintingFromCart.js
  server/database/queries/cart/index.js
  server/database/queries/cart/postCartQuery.js
  server/database/queries/index.js
  server/routes/cart.js
  server/routes/index.js
  server/routes/paintings.js
  test/deletePaintingCart.test.js
Labels: Awaiting Review, Backend

#39 37 filter painting
  server/controllers/paintings/getPaintings.js
  server/database/queries/Paintings/getPaintingCategory.js
  server/database/queries/Paintings/index.js
  server/database/queries/index.js
  server/routes/paintings.js
  test/paintings.test.js
Labels: Awaiting Review, Backend, Database

#40 GET | cart
  server/controllers/cart/getCart.js
  server/controllers/cart/index.js
  server/controllers/index.js
  server/database/queries/cart/getCart.js
  server/database/queries/cart/index.js
  server/database/queries/index.js
  server/routes/cart.js
  server/routes/index.js
  test/cart.test.js
Labels: Awaiting Review, Backend

#41 handle delete painting route
  server/app.js
  server/controllers/index.js
  server/controllers/paintings/deletePainting.js
  server/controllers/paintings/index.js
  server/database/queries/Paintings/deletePaintingsQuery.js
  server/database/queries/Paintings/index.js
  server/database/queries/index.js
  server/routes/paintings.js
  test/paintings.test.js
Labels: Awaiting Review, Backend

#43 42 admin controller
  server/controllers/auth.js
  server/controllers/index.js
  server/controllers/user/activateArtist.js
  server/controllers/user/getAllArtist.js
  server/controllers/user/index.js
  server/database/connection.js
  server/database/data/build.sql
  server/database/data/fakeData.sql
  server/database/queries/admin/getAdmin.js
  server/database/queries/admin/index.js
  server/database/queries/artists/getAllArtist.js
  server/database/queries/artists/index.js
  server/database/queries/artists/switchActivateArtist.js
  server/database/queries/index.js
  server/middleware/index.js
  server/middleware/protectedAdmin.js
  server/routes/artist.js
  server/routes/auth.js
  server/utils/validation/loginSchema.js
  test/artist.test.js
  test/auth.test.js
  test/cart.test.js
Labels: Awaiting Review, Backend, Database

#44 GET | Profile
  server/controllers/errorHandlers/index.js
  server/controllers/index.js
  server/controllers/user/getUserProfile.js
  server/controllers/user/index.js
  server/database/queries/customers/getCustomerProfile.js
  server/database/queries/customers/index.js
  server/database/queries/index.js
  server/routes/customer.js
  server/routes/index.js
  test/customer.test.js
Labels: Awaiting Review

#47 GET | reviews
  server/controllers/index.js
  server/controllers/review.js
  server/database/queries/index.js
  server/database/queries/review.js
  server/routes/index.js
  server/routes/review.js
  test/review.test.js
Labels: Awaiting Review, Backend

#48 46 post review
  server/controllers/index.js
  server/controllers/review.js
  server/database/queries/index.js
  server/database/queries/review.js
  server/routes/review.js
  server/utils/validation/addReviewSchema.js
  server/utils/validation/index.js
  test/review.test.js
Labels: Awaiting Review

#54 25 patch user
  server/controllers/errorHandlers/index.js
  server/controllers/index.js
  server/controllers/middleware/index.js
  server/controllers/middleware/verifyUser.js
  server/controllers/user/index.js
  server/controllers/user/updateUserInfo.js
  server/database/queries/customers/index.js
  server/database/queries/customers/updateCustomer.js
  server/database/queries/index.js
  server/middleware/index.js
  server/middleware/protectedAdmin.js
  server/routes/artist.js
  server/routes/customer.js
  server/routes/paintings.js
  server/utils/validation/index.js
  server/utils/validation/updateSchema.js
  test/customer.test.js
Labels: Awaiting Review, Backend

#49 15 buy product
  server/controllers/errorHandlers/index.js
  server/controllers/index.js
  server/controllers/paintings/buyPaintings.js
  server/controllers/paintings/deletePainting.js
  server/controllers/paintings/index.js
  server/database/data/build.sql
  server/database/data/fakeData.sql
  server/database/queries/Paintings/buyPaintings.js
  server/database/queries/Paintings/index.js
  server/database/queries/index.js
  server/routes/paintings.js
  server/utils/validation/buyPaintingsSchema.js
  server/utils/validation/index.js
  test/artist.test.js
  test/auth.test.js
  test/paintings.test.js
Labels: Awaiting Review, Backend, Database

#52 Convert promise
  server/controllers/middleware/verifyUser.js
  server/utils/uploadImg.js
  server/utils/verify.js
  test/paintings.test.js
Labels: Awaiting Review

#50 23 PATCH /artist
  server/controllers/errorHandlers/index.js
  server/controllers/index.js
  server/controllers/user/index.js
  server/controllers/user/updateArtist.js
  server/database/queries/artists/index.js
  server/database/queries/artists/updateArtistQuery.js
  server/database/queries/index.js
  server/routes/artist.js
  server/utils/validation/index.js
  server/utils/validation/updateArtistSchema.js
  test/artist.test.js
Labels: Awaiting Review, Backend

#56 PATCH artist/avatar
  server/controllers/index.js
  server/controllers/paintings/buyPaintings.js
  server/controllers/user/index.js
  server/controllers/user/updateArtistAvatar.js
  server/database/queries/Paintings/getPaintingCategory.js
  server/database/queries/Paintings/getPaintingsQuery.js
  server/database/queries/artists/index.js
  server/database/queries/artists/updateAvatarQuery.js
  server/database/queries/index.js
  server/routes/artist.js
  server/utils/validation/index.js
  server/utils/validation/updateArtistAvatarSchema.js
  test/artist.test.js
  test/e3dffc59e95fcbaf6a25e3bdaa4cd06e.jpg
  test/paintings.test.js
Labels: Awaiting Review, Backend

#58 GET | /is-auth
  server/controllers/auth.js
  server/routes/auth.js
  test/index.test.js
Labels: Awaiting Review, Backend

#66 Frontend file struct
  client/config-overrides.js
  client/lessVariables.js
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/app/index.js
  client/src/components/AddProduct/index.js
  client/src/components/AddProduct/style.css
  client/src/components/Admin/index.js
  client/src/components/Admin/style.css
  client/src/components/Cart/index.js
  client/src/components/Cart/style.css
  client/src/components/Details/index.js
  client/src/components/Details/style.css
  client/src/components/Landing/index.js
  client/src/components/Landing/style.css
  client/src/components/Login/index.js
  client/src/components/Login/style.css
  client/src/components/Register/index.js
  client/src/components/Register/style.css
  client/src/components/Review/index.js
  client/src/components/Review/style.css
  client/src/components/common/Card/index.js
  client/src/components/common/Card/style.css
  client/src/components/common/Footer/index.js
  client/src/components/common/Footer/style.css
  client/src/components/common/Navbar/index.js
  client/src/components/common/Navbar/style.css
  client/src/constants/routes.js
  client/src/containers/LandingPage/index.js
  client/src/containers/LandingPage/style.css
  client/src/containers/ProfilePage/index.js
  client/src/containers/ProfilePage/style.css
  client/src/index.js
  server/routes/auth.js
  test/auth.test.js
Labels: Done, Frontend

#67 login componant
  client/lessVariables.js
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/app/index.js
  client/src/app/style.css
  client/src/assets/images/login.svg
  client/src/components/Login/index.js
  client/src/components/Login/loginIcon.js
  client/src/components/Login/style.css
Labels: Awaiting Review, Frontend
