Repository GSG-G8/art-gallery, pull requests merged in 2020-07, with the labels that each got.

#75 make signup componant
  client/src/app/index.js
  client/src/components/Login/index.js
  client/src/components/Login/loginIcon.js
  client/src/components/Login/style.css
  client/src/components/Register/index.js
  client/src/components/Register/style.css
  server/utils/validation/registerSchema.js
Labels: Awaiting Review

#88 GET | painting/:paintingId
  server/controllers/index.js
  server/controllers/paintings/getPaintingInfo.js
  server/controllers/paintings/index.js
  server/database/queries/Paintings/getPaintingInfoQ.js
  server/database/queries/Paintings/index.js
  server/database/queries/index.js
  server/routes/paintings.js
Labels: Awaiting Review

#72 Is-Auth ? and Logout context
  client/src/Contexts/AuthorizationContext.js
  client/src/Contexts/LogoutContext.js
  client/src/app/index.js
  client/src/components/Login/index.js
  client/src/constants/routes.js
  server/controllers/auth.js
Labels: Awaiting Review

#79 PictureWall component
  client/package-lock.json
  client/package.json
  client/src/components/Mockup/HowToUse.js
  client/src/components/Mockup/index.js
  client/src/components/Mockup/style.css
Labels: Awaiting Review, Frontend

#91 fetch artist profile
  client/src/app/index.js
  client/src/components/EditArtistProfile/Profile.js
  client/src/containers/ProfilePage/index.js
Labels: Awaiting Review

#68 59 nodemailer
  package-lock.json
  package.json
  server/controllers/middleware/mail.js
  server/controllers/paintings/buyPaintings.js
  server/database/data/fakeData.sql
  server/database/queries/Paintings/buyPaintings.js
Labels: Approved, Backend

#63 Paintings container
  client/package-lock.json
  client/src/app/index.js
  client/src/components/PaintingSection/PaintingsSection.js.js
  client/src/components/PaintingSection/index.css
  client/src/components/PaintingSection/index.js
  client/src/containers/LandingPage/index.js
  server/app.js
  server/controllers/cart/addPaintingToCart.js
  server/database/data/fakeData.sql
  server/database/queries/Paintings/getArtistPaintsQuery.js
  server/database/queries/Paintings/getPaintingCategory.js
  server/database/queries/Paintings/getPaintingsQuery.js
  server/routes/artist.js
  test/artist.test.js
  test/paintings.test.js
Labels: Awaiting Review, Frontend

#89 Painting details component
  client/src/app/index.js
  client/src/components/Details/index.js
  client/src/components/Details/style.css
  client/src/components/Mockup/index.js
  client/src/components/Mockup/style.css
  client/src/components/PaintingSection/PaintingsSection.js.js
  test/paintings.test.js
Labels: Awaiting Review, Frontend

#71 Footer Component
  client/package-lock.json
  client/src/assets/images/.gitkeep
  client/src/assets/images/berwaz.png
  client/src/components/common/Footer/index.js
  client/src/components/common/Footer/style.css
  client/src/containers/LandingPage/index.js
Labels: Awaiting Review, Frontend

#73 Navbar Component
  client/package-lock.json
  client/src/app/index.js
  client/src/components/Landing/index.js
  client/src/components/Landing/style.css
  client/src/components/common/Navbar/index.js
  client/src/components/common/Navbar/style.css
  client/src/containers/LandingPage/index.js
Labels: Awaiting Review, Frontend

#85 Cart Page & Checkout Modal
  client/src/app/index.js
  client/src/app/style.css
  client/src/components/Cart/index.js
  client/src/components/Cart/style.css
  client/src/components/PaintingSection/PaintingsSection.js
  client/src/components/PaintingSection/index.js
  client/src/components/common/Navbar/index.js
  client/src/containers/CartPage/index.js
Labels: Awaiting Review, Frontend

#92 Edit profile form
  client/src/components/EditArtistProfile/Profile.js
  client/src/components/EditArtistProfile/index.js
  client/src/components/EditArtistProfile/style.css
  server/database/data/build.sql
  server/utils/validation/updateArtistSchema.js
Labels: Awaiting Review, Frontend

#80 slidershow component
  client/package-lock.json
  client/src/app/index.js
  client/src/assets/images/Calligraphy.jpg
  client/src/assets/images/EgyptPyramids.jpg
  client/src/assets/images/Jerusalem.jpg
  client/src/assets/images/Women.jpg
  client/src/components/common/Slider/index.js
  client/src/components/common/Slider/style.css
  client/src/containers/LandingPage/index.js
Labels: Awaiting Review, Frontend

#97 Style landing page
  client/package-lock.json
  client/src/assets/images/words.jpg
  client/src/components/Details/index.js
  client/src/components/Details/style.css
  client/src/components/EditArtistProfile/Profile.js
  client/src/components/Mockup/index.js
  client/src/components/Mockup/style.css
  client/src/components/PaintingSection/PaintingsSection.js
  client/src/components/PaintingSection/index.js
  client/src/components/PaintingSection/style.css
  client/src/components/ReviewForm/style.css
  client/src/components/common/Footer/index.js
  client/src/components/common/Footer/style.css
  client/src/components/common/Navbar/index.js
  client/src/components/common/Navbar/style.css
  client/src/components/common/Slider/index.js
  client/src/components/common/Slider/style.css
  client/src/containers/LandingPage/index.js
  client/src/containers/LandingPage/style.css
Labels: Done

#84 78 artist profile
  client/src/assets/images/defultUserImg.svg
  client/src/components/AddProduct/index.js
  client/src/components/AddProduct/style.css
  client/src/components/Login/index.js
  client/src/components/PaintingSection/PaintingsSection.js
  client/src/components/PaintingSection/style.css
  client/src/components/ProfileArtist/index.js
  client/src/components/ProfileArtist/style.css
  client/src/components/Register/index.js
  client/src/containers/ProfilePage/index.js
  server/controllers/errorHandlers/index.js
  server/controllers/paintings/addPainting.js
  server/controllers/user/updateArtistAvatar.js
  server/routes/paintings.js
  test/artist.test.js
  test/paintings.test.js
Labels: Awaiting Review

#103 add multible property for add product componant
  client/src/components/AddProduct/index.js
  client/src/components/AddProduct/style.css
Labels: Awaiting Review

#99 Modal for add review
  client/src/app/index.js
  client/src/components/Details/index.js
  client/src/components/EditArtistProfile/Profile.js
  client/src/components/PaintingSection/index.js
  client/src/components/ProfileArtist/index.js
  client/src/components/ProfileArtist/style.css
  client/src/components/Register/index.js
  client/src/components/Review/index.js
  client/src/components/Review/style.css
  client/src/components/ReviewForm/ReviewContainer.js
  client/src/components/ReviewForm/index.js
  client/src/components/ReviewForm/style.css
  server/controllers/paintings/getArtistPaints.js
  server/database/data/build.sql
  server/database/queries/review.js
  server/utils/validation/addReviewSchema.js
  test/paintings.test.js
Labels: Awaiting Review, Frontend

#98 make admin page
  client/package-lock.json
  client/package.json
  client/src/app/index.js
  client/src/components/Admin/index.js
  client/src/components/Admin/login/index.js
  client/src/components/Admin/style.css
  server/controllers/cart/deletePaintingCart.js
  server/controllers/index.js
  server/controllers/user/getAdminData.js
  server/controllers/user/index.js
  server/database/queries/admin/getAdmin.js
  server/database/queries/admin/index.js
  server/database/queries/index.js
  server/routes/artist.js
Labels: Frontend

#100 82 page not found
  client/src/assets/images/notFoundImg.svg
  client/src/components/PageNotFound/index.js
  client/src/components/PageNotFound/style.css
  client/src/components/common/Footer/index.js
  client/src/components/common/Footer/style.css
  client/src/components/common/Slider/index.js
Labels: Frontend, in progress

#107 Using Stripe to edit user's budget
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/components/PaintingSection/index.js
  client/src/containers/CartPage/CheckoutForm.js
  client/src/containers/CartPage/index.js
  client/src/containers/CartPage/style.css
  package-lock.json
  package.json
  server/controllers/index.js
  server/controllers/stripe.js
  server/database/queries/customers/editCustomerBudget.js
  server/database/queries/customers/index.js
  server/database/queries/index.js
  server/routes/customer.js
Labels: Awaiting Review, Backend, Frontend

#74 Readme
  README.md
Labels: Changes Requested
